import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Locale } from "@/lib/geo/countries";
import type { DesignExportBundle } from "@/lib/design/export-documentation";
import { formatBudgetThb } from "@/lib/design/budget-targets";

const PAGE = { width: 595.28, height: 841.89 };
const MARGIN = 48;
const LINE = 14;

function slugify(name: string): string {
  return (name || "planasia-design").replace(/[^\w\-]+/g, "-").slice(0, 40);
}

function labels(locale: Locale) {
  const en = {
    title: "Design Documentation Summary",
    project: "Project",
    owner: "Owner",
    location: "Location",
    type: "Building type",
    floors: "Floors",
    area: "Gross area",
    budget: "Estimated cost",
    budgetTarget: "Budget target",
    permit: "Permit compliance",
    permitPass: "Passed",
    permitFail: "Needs review",
    materials: "Material estimate",
    openings: "Door & window schedule",
    rooms: "Rooms",
    bankReady: "Bank-ready status",
    yes: "Yes",
    no: "No",
    generated: "Generated by Planasia",
  };
  if (locale === "th") {
    return {
      ...en,
      title: "สรุปเอกสารการออกแบบ",
      project: "โครงการ",
      owner: "เจ้าของ",
      location: "ที่ตั้ง",
      type: "ประเภทอาคาร",
      floors: "จำนวนชั้น",
      area: "พื้นที่รวม",
      budget: "ต้นทุนประมาณ",
      budgetTarget: "เป้างบ",
      permit: "การตรวจสอบใบอนุญาต",
      permitPass: "ผ่าน",
      permitFail: "ต้องตรวจสอบ",
      materials: "ประมาณการวัสดุ",
      openings: "ตารางประตู-หน้าต่าง",
      rooms: "ห้อง",
      bankReady: "สถานะพร้อมยื่นกู้",
      yes: "ใช่",
      no: "ไม่",
      generated: "สร้างโดย Planasia",
    };
  }
  return en;
}

export async function generateDocumentationSummaryPdf(
  bundle: DesignExportBundle,
  locale: Locale = "en",
): Promise<Uint8Array> {
  const L = labels(locale);
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE.width, PAGE.height]);
  let y = PAGE.height - MARGIN;

  const drawHeading = (text: string, size = 16) => {
    page.drawText(text, { x: MARGIN, y, size, font: fontBold, color: rgb(0.1, 0.25, 0.55) });
    y -= size + 8;
  };

  const drawLine = (text: string, size = 10, bold = false) => {
    if (y < MARGIN + 40) {
      page = pdf.addPage([PAGE.width, PAGE.height]);
      y = PAGE.height - MARGIN;
    }
    page.drawText(text.slice(0, 90), {
      x: MARGIN,
      y,
      size,
      font: bold ? fontBold : font,
      color: rgb(0.15, 0.15, 0.15),
    });
    y -= LINE;
  };

  const { project, materialEstimate, costBalance, permitCompliance, doorWindowSchedule, editorState } =
    bundle;

  drawHeading(L.title);
  drawLine(`${L.project}: ${project.projectName || "—"}`, 11, true);
  drawLine(`${L.owner}: ${project.ownerName || "—"}`);
  drawLine(`${L.location}: ${project.location || "—"}`);
  drawLine(`${L.type}: ${project.projectTypeCode ?? "residential"}`);
  drawLine(`${L.floors}: ${project.floors}`);
  y -= 6;

  drawHeading(L.area, 12);
  drawLine(`${costBalance.grossAreaSqm} m² (target ${costBalance.targetAreaSqm || "—"} m²)`);
  drawLine(`${L.budget}: ${formatBudgetThb(costBalance.totalEstimatedThb)}`);
  if (costBalance.maxBudgetThb > 0) {
    drawLine(
      `${L.budgetTarget}: ${formatBudgetThb(costBalance.maxBudgetThb)} (${costBalance.budgetUtilizationPct}%)`,
    );
  }
  drawLine(`${L.bankReady}: ${costBalance.bankReady ? L.yes : L.no}`);
  y -= 6;

  drawHeading(L.permit, 12);
  drawLine(
    `${permitCompliance.passed ? L.permitPass : L.permitFail} — ${permitCompliance.errorCount} errors, ${permitCompliance.warningCount} warnings`,
  );
  const failures = permitCompliance.results
    .filter((r) => !r.passed && r.message !== "Rule not applicable")
    .slice(0, 8);
  for (const f of failures) {
    drawLine(`• [${f.ruleCode}] ${locale === "th" ? f.messageTh : f.message}`.slice(0, 95), 9);
  }
  y -= 6;

  drawHeading(L.materials, 12);
  drawLine(`${formatBudgetThb(materialEstimate.totalThb)} (${materialEstimate.grossAreaSqm} m²)`);
  for (const line of materialEstimate.lines.slice(0, 10)) {
    drawLine(
      `• ${line.category} / ${line.material}: ${line.quantity} ${line.unit} — ฿${line.totalThb.toLocaleString()}`,
      9,
    );
  }
  y -= 6;

  drawHeading(L.openings, 12);
  drawLine(`${doorWindowSchedule.length} items`);
  for (const row of doorWindowSchedule.slice(0, 12)) {
    drawLine(`• ${row.type} — ${row.room} (${row.wall}, ${row.widthM}m, F${row.floor})`, 9);
  }
  y -= 6;

  drawHeading(L.rooms, 12);
  for (const room of editorState.rooms) {
    drawLine(`• ${room.name} ${room.width}×${room.depth}m (F${room.floor})`, 9);
  }

  page.drawText(L.generated, {
    x: MARGIN,
    y: MARGIN - 10,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return pdf.save();
}

export function downloadPdfBytes(bytes: Uint8Array, filename: string) {
  const blob = new Blob([Uint8Array.from(bytes)], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadJsonBundle(bundle: DesignExportBundle, projectName: string) {
  const slug = slugify(projectName);
  const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${slug}-documentation.json`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function documentationPdfFilename(projectName: string): string {
  return `${slugify(projectName)}-summary.pdf`;
}
