/**
 * Department of Public Works and Town & Country Planning (DPT) drawing standards.
 * Canonical reference: Smart A TYPE E golden standard (`templates/cad/golden-standard.json`).
 *
 * Platform role: define layout standards and sheet structure.
 * Vector geometry for each sheet is generated by external AI agents per
 * `templates/standards/sheet-vector-specs.json`.
 */
import goldenSpec from "../../../templates/cad/golden-standard.json";
import type { ScopeSectionId } from "@/lib/pdf/drawing-scope";

export const DPT_STANDARD = {
  id: goldenSpec.id,
  name: goldenSpec.name,
  nameTh: goldenSpec.nameTh,
  modelType: goldenSpec.modelType as string,
  sheetSize: goldenSpec.sheetSize as "A3",
  orientation: "landscape" as const,
  disciplines: goldenSpec.disciplines as string[],
  sourcePath: goldenSpec.sourcePath as string,
} as const;

/** A3 landscape in PDF points (1 pt = 1/72 inch). */
export const DPT_SHEET = {
  widthPt: 1190.55,
  heightPt: 841.89,
  marginPt: 40,
  titleBlockHeightPt: 90,
} as const;

/** Typical scales per DPT / Smart A convention. */
export const DPT_SCALES = {
  index: "N/A",
  sitePlan: "1:500",
  floorPlan: "1:100",
  roofPlan: "1:100",
  elevation: "1:100",
  section: "1:100",
  detail: "1:20",
  structural: "1:100",
  mep: "1:100",
} as const;

/**
 * Drawing phases aligned to the agreed 7-section construction scope.
 * Implement renderers one phase at a time.
 */
export const DPT_DRAWING_PHASES = [
  {
    id: "cover-index" as ScopeSectionId,
    order: 1,
    label: "Cover Sheet & Index",
    labelTh: "หน้าปกและสารบัญ",
    sheetPatterns: ["A0.00"],
  },
  {
    id: "floor-layouts" as ScopeSectionId,
    order: 2,
    label: "Floor Plans & Layouts",
    labelTh: "แปลนพื้นและการจัดวาง",
    sheetPatterns: ["A1.00", "A2.", "A3.00"],
  },
  {
    id: "elevations-sections" as ScopeSectionId,
    order: 3,
    label: "Elevations & Sections",
    labelTh: "รูปด้านและรูปตัด",
    sheetPatterns: ["A4.00", "A5.00"],
  },
  {
    id: "details" as ScopeSectionId,
    order: 4,
    label: "Detail Drawings",
    labelTh: "แบบขยาย",
    sheetPatterns: ["A6.00", "A7.00", "A8.00", "A9.00"],
  },
  {
    id: "structural" as ScopeSectionId,
    order: 5,
    label: "Structural Drawings",
    labelTh: "แบบโครงสร้าง",
    sheetPatterns: ["S1.00", "S2.00", "S3.00", "S4.00", "S5.00"],
  },
  {
    id: "sanitation-electrical" as ScopeSectionId,
    order: 6,
    label: "Sanitation & Electrical Systems",
    labelTh: "ระบบสุขาภิบาลและไฟฟ้า",
    sheetPatterns: ["SN-", "E-", "ME-", "AC-"],
  },
  {
    id: "specifications" as ScopeSectionId,
    order: 7,
    label: "Specifications & Data Sheets",
    labelTh: "ข้อกำหนดและแผ่นข้อมูล",
    sheetPatterns: ["S5.00"],
  },
] as const;

export type DptDrawingPhaseId = (typeof DPT_DRAWING_PHASES)[number]["id"];
