import type { ProjectType } from "@/lib/db/schema/project-types";
import type { CostBenchmark } from "@/lib/db/schema/cost-benchmarks";
import type { PermitRule } from "@/lib/db/schema/permit-rules";

export const CATALOG_SCHEMA_VERSION = 1;

export const SEED_PROJECT_TYPES: ProjectType[] = [
  {
    id: "pt_residential",
    code: "residential",
    name: {
      en: "Residential",
      th: "บ้านพักอาศัย",
      hi: "Residential",
      vi: "Nhà ở",
    },
    description: {
      en: "Detached houses, townhouses, small apartments — REA residential index",
      th: "บ้านเดี่ยว ทาวน์เฮาส์ อพาร์ทเมนต์ขนาดเล็ก — ดัชนี REA ที่อยู่อาศัย",
      hi: "Residential buildings",
      vi: "Nhà ở dân dụng",
    },
    defaultFloors: 2,
    maxFloors: 4,
    allowsBasement: true,
    structuralSystemOptions: ["rc_frame", "load_bearing_masonry"],
    applicableBuildingCodes: ["TH-BCA", "TIS-776"],
    costMatrixKey: "residential",
    permitRuleSetId: "rea_residential_v1",
    icon: "home",
    active: true,
    sortOrder: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "pt_commercial",
    code: "commercial",
    name: {
      en: "Commercial / Home Office",
      th: "อาคารพาณิชย์ / โฮมออฟฟิศ",
      hi: "Commercial",
      vi: "Thương mại",
    },
    description: {
      en: "Shophouses, offices, mixed-use — higher MEP and fire Type A requirements",
      th: "อาคารพาณิชย์ สำนักงาน ใช้ประโยชน์混合 — ระบบ MEP และไฟ Type A",
      hi: "Commercial and home office",
      vi: "Văn phòng và thương mại",
    },
    defaultFloors: 4,
    maxFloors: 8,
    allowsBasement: true,
    structuralSystemOptions: ["rc_frame", "steel_frame"],
    applicableBuildingCodes: ["TH-BCA", "TIS-776", "NFPA-101-ref"],
    costMatrixKey: "commercial",
    permitRuleSetId: "rea_commercial_v1",
    icon: "building",
    active: true,
    sortOrder: 2,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "pt_warehouse",
    code: "warehouse",
    name: {
      en: "Warehouse / Factory",
      th: "โกดัง / โรงงาน",
      hi: "Warehouse",
      vi: "Kho / Nhà máy",
    },
    description: {
      en: "Steel-frame warehouses and light industrial — high floor load capacity",
      th: "โกดังโครงสร้างเหล็ก โรงงาน — รับน้ำหนักบรรทุกสูง",
      hi: "Warehouse and factory",
      vi: "Kho bãi và nhà máy",
    },
    defaultFloors: 1,
    maxFloors: 3,
    allowsBasement: false,
    structuralSystemOptions: ["steel_frame", "pre_engineered_metal"],
    applicableBuildingCodes: ["TH-BCA", "TIS-776", "DOL-load-ref"],
    costMatrixKey: "warehouse",
    permitRuleSetId: "rea_warehouse_v1",
    icon: "warehouse",
    active: true,
    sortOrder: 3,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "pt_high_rise",
    code: "high_rise",
    name: {
      en: "High-Rise / Hotel",
      th: "อาคารสูง / โรงแรม",
      hi: "High-Rise",
      vi: "Cao tầng / Khách sạn",
    },
    description: {
      en: "Buildings ≥23m or ≥4 floors with public use — full fire & elevator compliance",
      th: "อาคารสูง ≥23 ม. หรือ ≥4 ชั้น — มาตรฐานไฟและลิฟต์ครบ",
      hi: "High-rise and hotel",
      vi: "Cao tầng và khách sạn",
    },
    defaultFloors: 8,
    maxFloors: 50,
    allowsBasement: true,
    structuralSystemOptions: ["rc_core_wall", "dual_system", "steel_frame"],
    applicableBuildingCodes: ["TH-BCA", "TIS-776", "NFPA-101-ref", "IBC-ref"],
    costMatrixKey: "high_rise",
    permitRuleSetId: "rea_highrise_v1",
    icon: "hotel",
    active: true,
    sortOrder: 4,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
];

/** REA-indexed cost per sqm by building type × tier (THB, Thailand). */
export const SEED_COST_BENCHMARKS: CostBenchmark[] = [
  // Residential
  { id: "cb_res_eco", projectTypeCode: "residential", costTier: "economy", region: "TH", constructionPerSqm: 14_500, currency: "THB", structuralMultiplier: 1.0, mepMultiplier: 1.0, finishesMultiplier: 0.92, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Basic residential", th: "ที่อยู่อาศัยพื้นฐาน" }, active: true },
  { id: "cb_res_std", projectTypeCode: "residential", costTier: "standard", region: "TH", constructionPerSqm: 20_500, currency: "THB", structuralMultiplier: 1.0, mepMultiplier: 1.05, finishesMultiplier: 1.0, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Standard family home", th: "บ้านครอบครัวมาตรฐาน" }, active: true },
  { id: "cb_res_pre", projectTypeCode: "residential", costTier: "premium", region: "TH", constructionPerSqm: 31_000, currency: "THB", structuralMultiplier: 1.08, mepMultiplier: 1.12, finishesMultiplier: 1.18, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Premium residential", th: "ที่อยู่อาศัยพรีเมียม" }, active: true },
  // Commercial
  { id: "cb_com_eco", projectTypeCode: "commercial", costTier: "economy", region: "TH", constructionPerSqm: 18_000, currency: "THB", structuralMultiplier: 1.05, mepMultiplier: 1.15, finishesMultiplier: 0.9, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Basic shophouse", th: "อาคารพาณิชย์พื้นฐาน" }, active: true },
  { id: "cb_com_std", projectTypeCode: "commercial", costTier: "standard", region: "TH", constructionPerSqm: 26_000, currency: "THB", structuralMultiplier: 1.1, mepMultiplier: 1.25, finishesMultiplier: 1.0, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Office / mixed-use", th: "สำนักงาน / ใช้ประโยชน์混合" }, active: true },
  { id: "cb_com_pre", projectTypeCode: "commercial", costTier: "premium", region: "TH", constructionPerSqm: 38_000, currency: "THB", structuralMultiplier: 1.15, mepMultiplier: 1.35, finishesMultiplier: 1.2, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Grade A office", th: "อาคารสำนักงานเกรด A" }, active: true },
  // Warehouse
  { id: "cb_wh_eco", projectTypeCode: "warehouse", costTier: "economy", region: "TH", constructionPerSqm: 9_500, currency: "THB", structuralMultiplier: 0.85, mepMultiplier: 0.7, finishesMultiplier: 0.75, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "PEB steel warehouse", th: "โกดังเหล็กสำเร็จรูป" }, active: true },
  { id: "cb_wh_std", projectTypeCode: "warehouse", costTier: "standard", region: "TH", constructionPerSqm: 13_500, currency: "THB", structuralMultiplier: 1.0, mepMultiplier: 0.85, finishesMultiplier: 0.88, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Standard factory", th: "โรงงานมาตรฐาน" }, active: true },
  { id: "cb_wh_pre", projectTypeCode: "warehouse", costTier: "premium", region: "TH", constructionPerSqm: 19_000, currency: "THB", structuralMultiplier: 1.12, mepMultiplier: 1.0, finishesMultiplier: 1.05, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Cold storage / heavy industrial", th: "ห้องเย็น / อุตสาหกรรมหนัก" }, active: true },
  // High-rise
  { id: "cb_hr_eco", projectTypeCode: "high_rise", costTier: "economy", region: "TH", constructionPerSqm: 28_000, currency: "THB", structuralMultiplier: 1.15, mepMultiplier: 1.2, finishesMultiplier: 0.9, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Budget condo/hotel", th: "คอนโด/โรงแรมประหยัด" }, active: true },
  { id: "cb_hr_std", projectTypeCode: "high_rise", costTier: "standard", region: "TH", constructionPerSqm: 42_000, currency: "THB", structuralMultiplier: 1.25, mepMultiplier: 1.35, finishesMultiplier: 1.0, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Mid-rise hotel/residential tower", th: "โรงแรม/ตึกที่อยู่อาศัย" }, active: true },
  { id: "cb_hr_pre", projectTypeCode: "high_rise", costTier: "premium", region: "TH", constructionPerSqm: 65_000, currency: "THB", structuralMultiplier: 1.35, mepMultiplier: 1.5, finishesMultiplier: 1.25, source: "REA-2025", sourceLabel: { en: "Thai REA Index 2025", th: "ดัชนี REA 2568" }, effectiveFrom: "2025-01-01", notes: { en: "Luxury hotel / Grade A tower", th: "โรงแรมหรู / อาคารสูงเกรด A" }, active: true },
];

export const SEED_PERMIT_RULES: PermitRule[] = [
  // Residential
  {
    id: "pr_res_setback",
    projectTypeCode: "residential",
    ruleSetId: "rea_residential_v1",
    ruleCode: "RES-SETBACK-01",
    category: "setback",
    legalReference: "Building Control Act B.E. 2522 — Ministerial Regulation on Building Design",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร พ.ศ. 2522 — กฎกระทรวงกำหนดการออกแบบอาคาร",
    title: { en: "Minimum setbacks", th: "ระยะรอบอาคารขั้นต่ำ" },
    requirement: { en: "Front ≥3m, rear ≥2m, sides ≥1.5m from plot boundary", th: "ด้านหน้า ≥3ม. ด้านหลัง ≥2ม. ด้านข้าง ≥1.5ม." },
    severity: "error",
    requiredDocuments: ["site_plan_1_500"],
    active: true,
    sortOrder: 1,
  },
  {
    id: "pr_res_pile_2f",
    projectTypeCode: "residential",
    ruleSetId: "rea_residential_v1",
    ruleCode: "RES-STR-02",
    category: "structural",
    legalReference: "Ministerial Regulation on Building Design — Foundation",
    legalReferenceTh: "กฎกระทรวง — ฐานราก",
    title: { en: "2-storey pile foundation", th: "ฐานรากเสาเข็ม 2 ชั้น" },
    requirement: { en: "2+ floors require pile foundation", th: "อาคาร 2 ชั้นขึ้นไป ต้องใช้ฐานรากเสาเข็ม" },
    requiredWhen: { field: "numberOfFloors", operator: "gte", value: 2 },
    validateField: "structuralSystem",
    severity: "error",
    active: true,
    sortOrder: 2,
  },
  // Commercial
  {
    id: "pr_com_fire_a",
    projectTypeCode: "commercial",
    ruleSetId: "rea_commercial_v1",
    ruleCode: "COM-FIRE-01",
    category: "fire_safety",
    legalReference: "Building Control Act — Fire Protection for Type A Buildings",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร — อาคารประเภท ก.",
    title: { en: "Type A fire protection", th: "มาตรการป้องกันอัคคีภัย อาคารประเภท ก." },
    requirement: { en: "Sprinklers + fire alarm for commercial use >300 sqm", th: "สปริงเกอร์ + สัญญาณเตือนไฟ สำหรับพื้นที่พาณิชย์ >300 ตร.ม." },
    requiredWhen: { field: "grossFloorAreaSqm", operator: "gt", value: 300 },
    validateField: "fireSafetyComplianceLevel",
    minValue: 1,
    severity: "error",
    requiredDocuments: ["fire_protection_plan", "smoke_control_diagram"],
    active: true,
    sortOrder: 1,
  },
  {
    id: "pr_com_parking",
    projectTypeCode: "commercial",
    ruleSetId: "rea_commercial_v1",
    ruleCode: "COM-PARK-01",
    category: "parking",
    legalReference: "Building Control Act — Parking Requirements for Commercial Buildings",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร — ที่จอดรถอาคารพาณิชย์",
    title: { en: "Commercial parking ratio", th: "อัตราที่จอดรถอาคารพาณิชย์" },
    requirement: { en: "Minimum 1 parking space per 30 sqm GFA", th: "ที่จอดรถอย่างน้อย 1 คัน ต่อ 30 ตร.ม. พื้นที่" },
    validateField: "parkingSpaces",
    severity: "warning",
    active: true,
    sortOrder: 2,
  },
  // Warehouse
  {
    id: "pr_wh_load",
    projectTypeCode: "warehouse",
    ruleSetId: "rea_warehouse_v1",
    ruleCode: "WH-STR-01",
    category: "structural",
    legalReference: "Ministerial Regulation — Industrial Building Load",
    legalReferenceTh: "กฎกระทรวง — น้ำหนักบรรทุกอาคารอุตสาหกรรม",
    title: { en: "Floor load capacity", th: "ความสามารถรับน้ำหนักพื้น" },
    requirement: { en: "Warehouse floor load ≥5 kN/m² for heavy storage", th: "พื้นโกดัง ≥5 kN/ตร.ม. สำหรับเก็บของหนัก" },
    validateField: "loadBearingCapacityKnSqm",
    minValue: 5,
    severity: "error",
    requiredDocuments: ["structural_calculation", "load_diagram"],
    active: true,
    sortOrder: 1,
  },
  {
    id: "pr_wh_env",
    projectTypeCode: "warehouse",
    ruleSetId: "rea_warehouse_v1",
    ruleCode: "WH-ENV-01",
    category: "environmental",
    legalReference: "Factory Act B.E. 2535 — Environmental Impact (referenced)",
    legalReferenceTh: "พ.ร.บ. โรงงาน — ผลกระทบสิ่งแวดล้อม (อ้างอิง)",
    title: { en: "EIA threshold", th: "เกณฑ์ EIA" },
    requirement: { en: "Factory GFA >10,000 sqm may require EIA report", th: "โรงงาน >10,000 ตร.ม. อาจต้องยื่น EIA" },
    requiredWhen: { field: "grossFloorAreaSqm", operator: "gt", value: 10000 },
    severity: "warning",
    requiredDocuments: ["eia_report_if_applicable"],
    active: true,
    sortOrder: 2,
  },
  // High-rise
  {
    id: "pr_hr_elevator",
    projectTypeCode: "high_rise",
    ruleSetId: "rea_highrise_v1",
    ruleCode: "HR-ELEV-01",
    category: "elevator",
    legalReference: "Building Control Act — Elevator Requirements for High-Rise Buildings",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร — ลิฟต์อาคารสูง",
    title: { en: "Elevator minimum", th: "จำนวนลิฟต์ขั้นต่ำ" },
    requirement: { en: "≥1 elevator per 4 floors; min 2 for buildings ≥8 floors", th: "≥1 ลิฟต์ ต่อ 4 ชั้น; ขั้นต่ำ 2 คัน สำหรับ ≥8 ชั้น" },
    requiredWhen: { field: "numberOfFloors", operator: "gte", value: 4 },
    validateField: "elevatorCount",
    minValue: 1,
    severity: "error",
    requiredDocuments: ["elevator_layout_plan", "elevator_spec_sheet"],
    active: true,
    sortOrder: 1,
  },
  {
    id: "pr_hr_fire",
    projectTypeCode: "high_rise",
    ruleSetId: "rea_highrise_v1",
    ruleCode: "HR-FIRE-01",
    category: "fire_safety",
    legalReference: "Building Control Act — High-Rise Fire Safety Systems",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร — ระบบความปลอดภัยอัคคีภัยอาคารสูง",
    title: { en: "High-rise fire systems", th: "ระบบดับเพลิงอาคารสูง" },
    requirement: { en: "Pressurized stair, sprinkler, fireman's lift, smoke control required", th: "บันไดปลอดควัน สปริงเกอร์ ลิฟต์ดับเพลิง ควบคุมควัน" },
    requiredWhen: { field: "buildingHeightM", operator: "gte", value: 23 },
    validateField: "fireSafetyComplianceLevel",
    severity: "error",
    requiredDocuments: ["fire_protection_plan", "pressurized_stair_detail", "smoke_control_report"],
    active: true,
    sortOrder: 2,
  },
  {
    id: "pr_hr_parking",
    projectTypeCode: "high_rise",
    ruleSetId: "rea_highrise_v1",
    ruleCode: "HR-PARK-01",
    category: "parking",
    legalReference: "Building Control Act — Parking for High-Rise / Hotel",
    legalReferenceTh: "พ.ร.บ. ควบคุมอาคาร — ที่จอดรถอาคารสูง/โรงแรม",
    title: { en: "High-rise parking", th: "ที่จอดรถอาคารสูง" },
    requirement: { en: "Minimum parking per local authority ratio (typically 1:40–80 sqm GFA)", th: "ที่จอดรถตามอัตราท้องถิ่น (โดยทั่วไป 1:40–80 ตร.ม.)" },
    validateField: "parkingSpaces",
    severity: "warning",
    requiredDocuments: ["parking_layout_plan"],
    active: true,
    sortOrder: 3,
  },
];
